My_Workspace2/book/book/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('detailsapp.urls'))
]

My_Workspace2/book/detailsapp/urls.py
from django.urls import path
from detailsapp import views
app_name = 'detailsapp'
urlpatterns =[
    path('',views.home ,name = 'home'),
    
    path('store/',views.store ,name = 'store'),
    path('bookentry/',views.bookentry ,name = 'bookentry'),
    path('get/',views.get_books,name = 'get')
    
]

My_Workspace2/book/detailsapp/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    bname = models.CharField(max_length=30)
    bprice = models.FloatField()
    
    def __str__(self):
        return self.bname


My_Workspace2/book/detailsapp/views.py
from django.shortcuts import render
from detailsapp.models import Book
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
# Create your views here.
def home(request):
    template = loader.get_template('home.html')
    res = template.render()
    return HttpResponse(res)

def store(request):
    template = loader.get_template('store.html')
    res = template.render(request=request)
    return HttpResponse(res)

def bookentry(request):
    if request.method =='POST':
        book=Book()
        book.bname = request.POST['bookname']
        book.bprice = request.POST['bookprice']
        
        book.save()
        return HttpResponseRedirect('/')
    
def get_books(request):
        
        book=Book.objects.all().values()
        lis = list(book)
        template = loader.get_template('get.html')
        res = template.render(context={'books':lis})
        return HttpResponse(res)

My_Workspace2/book/detailsapp/templates/get.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Details</title>
    <style>
        .get{
            display: flex;
            flex-direction: column;
            border: 2px solid black;
            justify-content: center;
            gap: 2px;
            width: 100px;
            align-items: center;
            margin-left: 37%;
            
        }
    </style>

</head>
<body>
        {% for book in books %}
            <div class="get">
                <div class="entry"> Name: {{book.bname}}</div>
                <div class="entry">Price: {{book.bprice}}</div>
            </div><br>
            
        {% endfor %}
</body>
</html>

My_Workspace2/book/detailsapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Library Management System </title>
    <Style>
        .head{
            background-color: aquamarine;
        }
        .heading{
            font-weight: bold;
            font-family: sans-serif;
            text-align: center;
            margin-top: 0px ;
        }
        .button{
            display: flex;
            justify-content: center;
        }
        .bu{
            width: 100px;
            height: 50px;
            border: 2px black solid;
            border-radius: 20px;
        }
        a{
            text-decoration: none;
            color: black;
        }
    </Style>
</head>
<body>
    <div class="head">
        <h1 class="heading">Book Management System</h1>
    </div>
    <div class="button">
        <button class="bu"><a href="{% url 'detailsapp:store' %}">Store</a></button>
        <button class="bu"><a href="{% url 'detailsapp:get' %}">Get</a></button>
    </div>
</body>
</html>

My_Workspace2/book/detailsapp/templates/store.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store</title>
    <style>
        .head{
            font-weight: bold;
            background-color: grey;
            text-align: center;
            color: white;
            font-family: sans-serif;
        }
        .form{
            padding-top: 20px;
            display: flex;
            justify-content: center;
            width: 300px;
            border:2px solid black;
            flex-direction: column;
            gap: 20px;
            align-items: center;
            border-radius: 30px;
            margin-left: 37%;
        }
        input{
            
            height: 20px;
        }
        label{
            color:grey;
            font-family: sans-serif;

        }
        .sub{
            width: 90px;
            height: 40px;
            border-radius: 10px;
        }
        .bu{
            padding-bottom: 10px;
        }
        .sub:hover{
            background-color: gray;
        }
        
    </style>
</head>
<body>
    <div>
        <h1 class="head">Store your Details Here</h1>
    </div>
    <div>
        <form action="{% url 'detailsapp:bookentry'%}" method="post" class="form">
            {% csrf_token %}
            <div class="field">
                <label for="bookname" >Book_name :</label>
                <input type="text"  name = "bookname" placeholder="Enter your book name...">
            </div>
            <div class="field">
                <label for="bookprice">Book_price :</label>
                <input type="text" name = "bookprice" placeholder="Enter your book book price...">
            </div>
            <div class="bu">
                <button class="sub">Submit</button>
            </div>
        </form>
    </div>
</body>
</html>