My_Workspace2/day7/OTS/urls.py
from django.urls import path
from OTS.views import *
app_name='OTS'
urlpatterns = [
    path('',welcome),
    path('new-candidate',candidateRegistrationForm,name='registrationForm'),
    path('store-candidate',candidateRegistration,name='storeCandidate'),
    path('login',loginView,name='login'),
    path('home',candidateHome, name='home'),
    path('test-paper',testPaper,name='testPaper'),
    path('calculate-result',calculateTestResult,name='calculateTest'),
    path('test-history',testResultHistory,name='testHistory'),
    path('result',showTestResult,name='result'),
    path('logout',logoutView,name='logout'),
]

My_Workspace2/day7/day7/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("OTS/",include('OTS.urls')),
]

My_Workspace2/day7/OTS/models.py
from django.db import models
class Candidate(models.Model):
    username=models.CharField(primary_key=True,max_length=20)
    password=models.CharField(null=False, max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)
    def __str__(self):
        return self.username
class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)
class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()
# Create your models here.


# Create your models here.

My_Workspace2/day7/OTS/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import *
import random

def welcome(request):
    template=loader.get_template('welcome.html')
    res=template.render()
    return HttpResponse(res)
def candidateRegistrationForm(request):
    res=render(request,'registration_form.html')
    return res
def candidateRegistration(request):
    if request.method=='POST':
        username=request.POST['username']
        #Check if the user already exists
        if(len(Candidate.objects.filter(username=username))):
            userStatus=1
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['password']
            candidate.name=request.POST['name']
            candidate.save()
            userStatus=2
    else:
        userStatus=3 #Request method is not POST
    context={
        'userStatus':userStatus
    }
    res=render(request,'registration.html',context)
    return res
         
         

def loginView(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        candidate = Candidate.objects.filter(username = username ,password = password)
        if len(candidate)==0:
            loginError = "Invalid username or password"
            res = render(request , 'login.html',{'loginError':loginError})
        else:
            request.session['username'] = candidate[0].username
            request.session['name'] = candidate[0].name
            res = HttpResponseRedirect("home")
    else:
        res = render(request , 'login.html')
    return res
def candidateHome(request):
    if 'name' not in request.session.keys():
        res =HttpResponse('login')
    else:
        res = render(request, 'home.html')
        return res 
def testPaper(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    #fetch question from database table
    n=int(request.GET['n'])
    question_pool=list(Question.objects.all())
    random.shuffle(question_pool)
    questions_list=question_pool[:n]
    context={'questions':questions_list}
    res=render(request,'test_paper.html',context)
    return res  

def calculateTestResult(request):
    pass  
def testResultHistory(request):
    pass  
def showTestResult(request):
    pass
   
def logoutView(request):
    if 'name' in request.session.keys():
        del request.session['username']
        del request.session['name']
    return HttpResponseRedirect("login")

    

# Create your views here.

My_Workspace2/day7/OTS/templates/home.html
{% extends 'main.html' %}

{% block title%} Welcome to home page {%endblock%}

{% block top %}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>
<a href="{% url 'OTS:logout' %}">Logout</a>

{% endblock %}

{% block content %}
    <h1>Welcome {{request.session.name}}, to your home page</h1>
        <div class="button-link">
            <a href="{% url 'OTS:testPaper' %}?n=1">Test of 1 Question</a>
        </div>
        <div class="button-link">
            <a href="{% url 'OTS:testPaper' %}?n=3">Test of 3 Question</a>
        </div>
        <div class="button-link">
            <a href="{% url 'OTS:testPaper' %}?n=5">Test of 5 Question</a>
        </div>

<div class="button-link">
<a href="{% url 'OTS:testHistory' %}">Test History</a>
</div>
{% endblock %}

My_Workspace2/day7/OTS/templates/login.html
{% extends 'main.html' %}

{% block title%} OTS - Login Form {%endblock title%}
{% block top%}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>

{%endblock %}
{% block content %}
<div class="all-forms">
{% if loginError%}
<div id="error">{{loginError}}</div>
{% endif %}
<form action="{% url 'OTS:login' %}" method="POST">
{% csrf_token %}
<div class="form-unit">
<label for="username">Username</label>
<input type="text" name="username">
</div>
<div class="form-unit">
<label for="password">Password</label>
<input type="password" name="password">
</div>
<div class="form-unit">
<input type="submit" value="Login">
<input type="reset" value="Clear">
</div>
</form>
New user<a href="{% url 'OTS:registrationForm' %}">Click Here</a>

</div>
{% endblock %}

My_Workspace2/day7/OTS/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head> 
<body>
    <div><h1>Online Testing System</h1></div>
    <div>
        {% block top %}{% endblock %}
    </div>
    <div>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

My_Workspace2/day7/OTS/templates/registration.html
{% extends 'main.html' %}

{% block title%} Welcome to Registration Status  {%endblock%}

{% block top %}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>
<a href="{% url 'OTS:login' %}">login</a>

{% endblock %} 

{% block content %}
{% if userStatus == 1 %}
<div>
    Sorry, username already exists, please try different username.
</div>

{% elif userStatus == 2 %}
<div>
    Congratulations!! , User created successfully
</div>
{% elif userStatus == 3 %}
<div>
    Oops!!, Improper Request
</div>
{% endif %}
{% endblock %}

My_Workspace2/day7/OTS/templates/registration_form.html
{% extends 'main.html' %}
{% block title%} Welcome to Registration from System {%endblock%}
{% block top %}
<a href="{% url 'OTS:login' %}">login</a>
{% endblock %} 


{% block content %}
<div>
    <form action="{% url 'OTS:storeCandidate' %}" method="post">
        {% csrf_token %}
        <label for="username">Username</label>
        <input type="text" name="username"><br>
        <label for="password">Password</label>
        <input type="password" name="password"><br>
        <label for="name">Name</label>
        <input type="text" name="name"><br>
        
        
        <input type="submit" value="Submit">
        <input type="reset" value="Clear">   

    </form>
    Already have an account,<a href="{% url 'OTS:login' %}">click here</a>
</div>
{% endblock %}

My_Workspace2/day7/OTS/templates/test_paper.html
{% extends 'main.html' %}

{% block title%} OTS - Test Paper {%endblock title%}
{% block top%}
{%endblock %}
{% block content %}
<form action="{% url 'OTS:calculateTest' %}" method="post">
{% csrf_token %}
{% for question in questions %}
<div class="question">
<input type="hidden" name="{{question.qid}}" value="{{question.qid}}">
{{question.que}}
</div>
<div class="options"><input type="radio" name="q{{question.qid}}" value="a">{{question.a}}</div>
<div class="options"><input type="radio" name="q{{question.qid}}" value="b">{{question.b}}</div>
<div class="options"><input type="radio" name="q{{question.qid}}" value="c">{{question.c}}</div>
<div class="options"><input type="radio" name="q{{question.qid}}" value="d">{{question.d}}</div>

{% endfor %}
<div><input type="submit" value="Submit"></div>
</form>
{% endblock %}

My_Workspace2/day7/OTS/templates/welcome.html
{% extends 'main.html' %}

{% block title%} Welcome to Online Testing System {%endblock%}

{% block top %}
<a href="{% url 'OTS:registrationForm' %}">Signup</a>
<a href="{% url 'OTS:login' %}">login</a>

{% endblock %} 

{% block content %}
<p>Welcome to Online Testing System</p>
{% endblock %}