My_Workspace2/day8project/day8project/urls.py
from django.contrib import admin
from django.urls import path
from  django.conf.urls import include


urlpatterns = [
    path('mlapp/',include('mlapp.urls')),
    path('admin/', admin.site.urls),
]

My_Workspace2/day8project/mlapp/urls.py
from django.urls import path
from mlapp.views import *
app_name = 'mlapp'

urlpatterns = [
    path('home/',home),
    path('result/',result ,name='result'),
]

My_Workspace2/day8project/mlapp/models.py
from django.db import models

# Create your models here.

My_Workspace2/day8project/mlapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
import joblib

# Create your views here.
def home(request):
    template=loader.get_template('home.html')
    return HttpResponse(template.render())

def result(request):
    cls = joblib.load('glassmlmodel.sav')
    lis = []
    lis.append(request.GET['RI'])
    lis.append(request.GET['Na'])
    lis.append(request.GET['Mg'])
    lis.append(request.GET['Al'])
    lis.append(request.GET['Si'])
    lis.append(request.GET['K'])
    lis.append(request.GET['Ca'])
    lis.append(request.GET['Ba'])
    lis.append(request.GET['Fe'])
    
    ans = cls.predict([lis])
    
    return render(request,'result.html',{'ans':ans ,'lis':lis})


My_Workspace2/day8project/mlapp/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ML_model</title>
</head>
<body>
    <div>
        <h1>This is Home Page</h1>
    </div>
    <div>
        <form action="{%url 'mlapp:result'%}">
            {% csrf_token %}
            RI: <input type="text" required name="RI">
            <br><br>
            Na: <input type="text" required name="Na">
            <br><br>
            Mg: <input type="text" required name="Mg">
            <br><br>
            Al: <input type="text" required name="Al">
            <br><br>
            Si: <input type="text" required name="Si">
            <br><br>
            K: <input type="text" required name="K">
            <br><br>
            Ca: <input type="text" required name="Ca">
            <br><br>
            Ba: <input type="text" required name="Ba">
            <br><br>
            Fe: <input type="text" required name="Fe">
            <br><br>
            <input type="submit" name="" value="submit">

        </form>
    </div>
</body>
</html>

My_Workspace2/day8project/mlapp/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Result Page</title>
</head>
<body>
    <div>
        <h1>This is Result Page</h1>
        <br>
        <h1> Entered data by User {{lis}}</h1>
        <br>
        <h1>The Result is {{ans}}</h1>
        <br>
        <p>
            Type of glass: (class attribute)
            -- 1 building_windows_float_processed
            -- 2 building_windows_non_float_processed
            -- 3 vehicle_windows_float_processed
            -- 4 vehicle_windows_non_float_processed (none in this database)
            -- 5 containers
            -- 6 tableware
            -- 7 headlamps
        </p>
    </div>
</body>
</html>